version: '3.8'

services:
  web:
    image: aimzer/cvrt_hexp
    build: ./services/web
    command: gunicorn --bind 0.0.0.0:9000 -w 4 manage:app
    ports:
      - 9000:9000
    env_file:
      - ./.env.prod
    volumes:
      - /home/aimen/projects/nivturk/services/web/app/static/human_exp_images:/home/app/web/app/static/human_exp_images
      - /home/aimen/projects/nivturk/services/web/user_data:/home/app/web/user_data
